export const FETCH_PATIENT ="FETCH_PATIENT";
export const FETCH_DEPARTMENT ="FETCH_DEPARTMENT";
export const FETCH_SYMPTOMS ="FETCH_SYMPTOMS";
export const FETCH_COMOBIDITY ="FETCH_COMOBIDITY";
export const FETCH_TESTS ="FETCH_TESTS";
export const FETCH_TEST_RESULTS ="FETCH_TEST_RESULTS";
export const FETCH_DIAGNOSIS ="FETCH_DIAGNOSIS";
export const FETCH_TREATMENT ="FETCH_TREATMENT";